### ISSUE TITLE
Update das bibliotecas

### ISSUE THREAD

**Issue by jonatasoli** [jonatasoli/fast-ecommerce-admin#14]
Rodar o comando `yarn outdated` e verificar pacotes desatualizados e fazer suas atualizações.

Também é necessário testar todas as funcionalidades do projeto pra ver se houve algum break change.

**Comment by Jpcampos123** [comment]
fiz essas atualizações por aqui commit - 1b85738a92598148a46d422efa44f938cce3bfe6

**Comment by jonatasoli** [comment]
![screenshot-2024-09-20-18-13-52](https://github.com/user-attachments/assets/422d3b11-978d-4854-8979-f7950e6f6eaa)
tem alguns ainda ali pelo que vi.
